/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#0f172a",
        "surface-dim": "#020617",
        "surface-bright": "#1e293b",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#0f172a",
        "surface-container": "#1e293b",
        "surface-container-high": "#334155",
        "surface-container-highest": "#475569",
        "surface-variant": "#1e293b",
        "surface-muted": "#0f172a",
        "surface-tint": "#334155",
        "on-surface": "#f8fafc",
        "on-surface-variant": "#94a3b8",
        "inverse-surface": "#f8fafc",
        "inverse-on-surface": "#000000",
        outline: "#475569",
        "outline-variant": "#334155",
        primary: "#ffffff",
        "on-primary": "#000000",
        "primary-container": "#334155",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#000000",
        "primary-fixed": "#334155",
        "primary-fixed-dim": "#1e293b",
        "on-primary-fixed": "#ffffff",
        "on-primary-fixed-variant": "#94a3b8",
        secondary: "#2563eb",
        "on-secondary": "#ffffff",
        "secondary-container": "rgba(37, 99, 235, 0.15)",
        "on-secondary-container": "#93c5fd",
        "secondary-fixed": "rgba(37, 99, 235, 0.1)",
        "secondary-fixed-dim": "rgba(37, 99, 235, 0.05)",
        "on-secondary-fixed": "#93c5fd",
        "on-secondary-fixed-variant": "#60a5fa",
        tertiary: "#0ea5e9",
        "on-tertiary": "#ffffff",
        "tertiary-container": "rgba(14, 165, 233, 0.15)",
        "on-tertiary-container": "#7dd3fc",
        "tertiary-fixed": "rgba(14, 165, 233, 0.1)",
        "tertiary-fixed-dim": "rgba(14, 165, 233, 0.05)",
        "on-tertiary-fixed": "#7dd3fc",
        "on-tertiary-fixed-variant": "#38bdf8",
        error: "#ef4444",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#7f1d1d",
        background: "#020617",
        "on-background": "#f8fafc",
        "text-secondary": "#94a3b8",
        "border-metallic": "#334155",
        "glow-accent": "rgba(37, 99, 235, 0.15)",
        "neon-green": "#10b981",
        "neon-yellow": "#f59e0b",
        "neon-purple": "#3b82f6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-desktop": "80px",
        "margin-mobile": "24px",
        "section-gap": "160px",
      },
      fontFamily: {
        "headline-display": ["Inter", "Poppins", "sans-serif"],
        "headline-lg": ["Inter", "Poppins", "sans-serif"],
        "headline-lg-mobile": ["Inter", "Poppins", "sans-serif"],
        "body-md": ["Poppins", "sans-serif"],
        "label-caps": ["Poppins", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-mono": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.2em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-display": ["84px", { lineHeight: "92px", letterSpacing: "-0.04em", fontWeight: "600" }],
      },
      animation: {
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "spin-slow": "spin 20s linear infinite",
        "float": "float 6s ease-in-out infinite",
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        }
      }
    },
  },
  plugins: [],
}
